dist: xenial
language: python
python:
  - 3.6

before_install:
  # as of tox v3.10.0, the installed virtualenv is used, make sure it is up to date
  - pip install -U pip setuptools virtualenv tox codecov

script:
  - tox -e py36

after_success:
  - codecov

branches:
  only:
    - master
